name: deploy-docs

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pages: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            # Compile package with in-source build
            - name: Install
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
                python setup.py install  # do not use "pip install ." as it fails

            # Build sphinx in /docs/build, copy /docs/doxygen/output/html to /docs/build/doxygen
            - name: Build Sphinx
              run: |
                sudo apt-get install pandoc -y
                python -m pip install -r docs/requirements.txt
                export PATH=$HOME/.local/bin:$PATH
                make clean html --directory=docs
                touch docs/build/html/.nojekyll
                echo 'Visit [Documentation](https://ameli.github.io/freealg/index.html).' > docs/build/html/README.md

            # - name: Build JupyterLite
            #   run: |
            #     pip install jupyterlite jupyterlite-pyodide-kernel jupyter-server wheel
            #     # mkdir -p wheels
            #     # pip download --no-deps --only-binary=:all: --dest wheels freealg
            #     # pip download --no-deps --dest wheels freealg
            #     pip install build
            #     python -m build --sdist --wheel --outdir wheels .
            #     ls -l wheels      # debug
            #     jupyter lite build \
            #       --contents notebooks \
            #       --output-dir docs/build/html/jlite \
            #       --piplite-wheels $(ls wheels/*)
            #       # --piplite-wheels wheels/*.whl

            # Deploy to github pages
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: docs/build/html
                branch: gh-pages
                token: ${{ secrets.GITHUB_TOKEN }}
